# Generated by Django 4.0.4 on 2022-05-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipes_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image1',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image2',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image3',
            field=models.ImageField(upload_to='images'),
        ),
    ]
