# Generated by Django 4.0.4 on 2022-05-23 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recipes_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
