# Generated by Django 4.0.4 on 2022-05-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe',
            field=models.TextField(verbose_name='Recipe'),
        ),
    ]
