# Generated by Django 4.0.4 on 2022-05-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_account_email_en_remove_account_email_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_en',
            field=models.TextField(null=True, verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='recipe_ru',
            field=models.TextField(null=True, verbose_name='Recipe'),
        ),
    ]
