# Generated by Django 4.0.4 on 2022-06-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_favouritepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouritePost',
        ),
    ]
