version: '3.10'

services:
  web:
    build: .
    command: python ./firstapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/firstapp/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./firstapp/firstapp/.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: